GET http://localhost:3001/api/persons/

###
DELETE http://localhost:3001/api/persons/1

###
POST http://localhost:3001/api/persons/ HTTP/1.1
content-type: application/json

{
    "name": "Arno Newman",
    "number": "075-1998-9089"
}
